version: '3.2'

services:
  app:
    container_name: boilerplate-app
    build: .
    ports:
    - 8080:8080
    networks:
      - backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://database:5432/boilerplate'
    restart: on-failure:5

  database:
    container_name: boilerplate-db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    networks:
      - backend
      - admin
    volumes:
      - boilerplate-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'boilerplate'
      POSTGRES_PASSWORD: 'b0il3rpl4t3'
      POSTGRES_DB: 'boilerplate'
    restart: unless-stopped

  adminer:
    container_name: boilerplate-adminer
    image: adminer:4.7.6
    ports:
      - 9090:8080
    networks:
      - admin
    depends_on:
      - database
    restart: unless-stopped

  sonar:
    container_name: boilerplate-sonar
    image: sonarqube:8.6.1-community
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    restart: unless-stopped

volumes:
  boilerplate-db-data:

networks:
  backend:
  admin: